#include "globals.h"
uint32_t colorR;
uint32_t colorG;
uint32_t colorB;
uint32_t brightness;
uint8_t currentHour;
uint8_t currentMinute;
long currentTime;
int temperature;
int humidity;
int tempStatus;